#### Todas las reparaciones
GET http://localhost:9090/api/reparacion-adicional


#### reparaciones por estimacion
GET http://localhost:9090/api/reparacion-adicional/1

#### reparaciones por estimacion
GET http://localhost:9090/api/reparacion-adicional/individual/1


### Agregar reparacion
POST http://localhost:9090/api/reparacion-adicional
Content-Type: application/json

{
    "estimacion_id": 1,
    "reparacion_adicional_detalle": "Alineamiento de Ruedas",
    "valor_reparacion": "650.00",
    "tipo": "Normal"
}

#### Actualizar reparacion
PUT http://localhost:9090/api/reparacion-adicional/15
Content-Type: application/json

{    
    "estimacion_id": 1,
    "reparacion_adicional_detalle": "Alineamiento de Ruedas",
    "valor_reparacion": "650.00",
    "tipo": "Normal"
}


#### Borrar reparacion
DELETE http://localhost:9090/api/reparacion-adicional/1